### ISSUE TITLE
successful builds reported as failure

### ISSUE THREAD

**Issue by cdot65** [carlmontanari/boxen#42]
I am receiving conflicting bits of feedback from boxen's package process. It's reported that stderr had had reported an issue during the build process, but I have been unable to track it down while performing a `tail -f ` operation on the logs.

Console output

```
❯ boxen package --disk ./PA-VM-KVM-10.2.3.qcow2
      info   1673194745 package requested for disk './PA-VM-KVM-10.2.3.qcow2'
     debug   1673194745 temporary directory '/tmp/boxen1983071850' created successfully
     debug   1673194772 disks allocated for packaging
     debug   1673194772 packaging instance created
     debug   1673194772 bundling required packaging files complete
     debug   1673194772 pre packaging complete, begin docker-ization!
      info   1673194772 docker build output available at '/tmp/boxen1983071850/initial_build.log'
  critical   1673195173 error running instance installation: commandError: stderr contains output but it shouldn't
        🆘 finished unsuccessfully in 428 seconds
commandError: stderr contains output but it shouldn't
```

debug logs leave me with the impression that all is well https://pastebin.com/tAfVDxH3

```
Step 12/13 : RUN curl http://10.20.40.1:6666/disk.qcow2 -o disk.qcow2
 ---> Running in 915b96541217
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 8784M  100 8784M    0     0   616M      0  0:00:14  0:00:14 --:--:--  591M
Removing intermediate container 915b96541217
 ---> 04a55404f805
Step 13/13 : ENTRYPOINT ["boxen", "package-install"]
 ---> Running in e27dda6c9751
Removing intermediate container e27dda6c9751
 ---> bb8757ef2aaa
Successfully built bb8757ef2aaa
Successfully tagged boxen_paloalto_panos:10.2.3
^[
```

docker images show an extremely large container image

```
❯ docker images
REPOSITORY             TAG       IMAGE ID       CREATED          SIZE
boxen_paloalto_panos   10.2.3    bb8757ef2aaa   13 minutes ago   10.7GB
<none>                 <none>    9185389db3d3   26 minutes ago   10.7GB
ubuntu                 20.04     d5447fc01ae6   4 weeks ago      72.8MB
```

environment has SPARSIFY enabled, leaving me to believe that this stage never gets executed, but that's all a guess at this point.

```
❯ env | grep BOXEN
BOXEN_SPARSIFY_DISK=1
BOXEN_LOG_LEVEL=debug
```

host os build information

```
❯ hostnamectl
 Static hostname: hou-net-01.redtail.com
       Icon name: computer-server
         Chassis: server 🖳
      Machine ID: 187c768704324a158cebf94b0620a0e4
         Boot ID: 55fa62562de84c28956fd7fdae3c78b1
Operating System: AlmaLinux 9.1 (Lime Lynx)
     CPE OS Name: cpe:/o:almalinux:almalinux:9::baseos
          Kernel: Linux 5.14.0-162.6.1.el9_1.x86_64
    Architecture: x86-64
 Hardware Vendor: Dell Inc.
  Hardware Model: PowerEdge R720xd
```

**Comment by carlmontanari** [comment]
woof. the pan image keeps coming back to haunt us 🤣 

its been a minute since ive been poking around in boxen , but I *think* this looks like the "initial packaging" works, but then the install phase fails. basically boxen does a first round of building a container with the disk image and the boxen binary in it -- we see that complete successfully in the pastebin bits.

after that we then start that container - the purpose of this step is to boot the vm up all the way, handle all the initial config dialog things, then save *that* image as the "final" container image (*final as an asterisk because if you have sparsify enabled there is one more step of actually doing that process). 

if I had to guess (and im very rusty on this so Im sorry for that!) we get to the point where we try to boot the pan disk and we see some cpu flag missing or something similar. you can try to reproduce this by overriding the entry point of that giant image and running the container. from there you can either try to boot the pan up manually w/ the qemu command, or you could run boxen binary. either way I think we should see some output w/ some complaints. the worst case scenario here is that boxen sees the output and exits before its logged. in that case I think we can do boxen dev mode thing -- that causes boxen to *not* nuke the temp directory that all the build things happen in. in that directory we should be writing the logs out to disk. worst case you can hopefully find the qemu launch command, then do that manually to see what shakes out.

hth!

**Comment by cdot65** [comment]
Carl, thanks for the detailed reply and I believe you're on the right track. 

This is a new host, and after installing KVM I failed to really give it a go. I believe one of my kernel flags for enabling cgroup 'devices' is failing the vibe check. I am going to swap this over to Ubuntu to see if my results improve.

```
❯ virt-host-validate
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : WARN (Enable 'devices' in kernel Kconfig file or mount/enable cgroup controller in your system)
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : PASS
  QEMU: Checking if IOMMU is enabled by kernel                               : PASS
  QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)
```

however my system's GRUB arguments check out

```
GRUB_CMDLINE_LINUX="resume=/dev/mapper/almalinux-swap rd.lvm.lv=almalinux/root rd.lvm.lv=almalinux/swap rhgb quiet intel_iommu=on cgroup_enable=cpuset cgroup_enable=cpu cgroup_enable=devices cgroup_enable=freezer cgroup_enable=blkio"
```

**Comment by cdot65** [comment]
This should be chalked up to a host configuration issue, unrelated to the boxen project

**Comment by carlmontanari** [comment]
ah nice! glad you've got things rolling along! I saw the warnings in the validate stuff but what was the final fix?

also I wonder if it could be solved w/ using different cpu emulation flags (like [here](https://github.com/carlmontanari/boxen/blob/main/boxen/platforms/paloaltopanos.go#L37))? I've defo had to futz about with these flags before... though mostly it's just blindly testing stuff :) tbh, it's all a bit of dark magic w/ so many moving parts!

thanks for the update Calvin!
